version: "2"
services:

  jupyter:
    build:
      context: ./jupyter
    ports:
      - "8888:8888"
    links:
      - postgis
    volumes:
          - "./notebooks:/notebooks" 
          - "./data:/data"
          - home-volume:/home
    mem_limit: 16G

  postgis:
    image: mdillon/postgis
    restart: always
    environment:
      POSTGRES_USER: data
      POSTGRES_PASSWORD: data
      POSTGRES_DB: data

volumes:
  home-volume:
    external: false